name: Reusable workflow example

on:
  workflow_call:
    inputs:
      SHA:
        required: true
        type: string
        default: ''
    
jobs:
  call-existing-workflow:
    - uses: ./.github/workflows/test.yml
      with:
        SHA: ${{ inputs.SHA }}
        