name: Updated Go Workflow
on:
  workflow_call:
    # inputs:
    #   SHA:
    #     required: false
    #     type: string
    #     default: ''
permissions: read-all
jobs:
  updated-job:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        ref: $GITHUB_SHA
    - run: echo 'Hello from test ////////////
